name: Test
on: [push]

jobs:
  standard_tests:
    name: Tests with ${{ matrix.config.name }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: oi4ai/bout3d:db-outer-${{ matrix.config.mode }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - name: debugging
            mode: debug
          - name: optimisations
            mode: opt
    steps:
      - name: Job information
        run: |
          echo Build: ${{ matrix.config.name }}, ${{ matrix.config.os }}
          echo CMake options: ${{ matrix.config.cmake_options }}
          cat /etc/os-release

      - name: Setup dependencies
        run: |
          sudo dnf install -y git-lfs

      - name: Checkout hermes-2
        run: |
          cd /home/boutuser/
          git clone ${{ github.server_url }}/${{ github.repository }} -b ${{ github.ref_name }} hermes-2
          cd hermes-2
          git checkout ${{ github.sha }}
          git submodule update --init --recursive

      - name: Build
        run: |
          cd /home/boutuser/hermes-2
          cmake --version
          cmake -S . -B build -Dbout++_DIR=/home/boutuser/BOUT-dev/build
          make -C build -j 2

      - name: Run
        run: |
          cd /home/boutuser/hermes-2
          # Run only shortly
          sed -e 's/nout = .*/nout = 1/' -i */BOUT.inp
          sed -e 's/timestep = 100/timestep = 1/' -i */BOUT.inp
          # Change solver type - beuler is quite heavy on setup, but we want
          # to run only short
          sed -e 's/type = beuler/type = pvode/' -i */BOUT.inp
          build/hermes-2 -d 1-lowres
          build/hermes-2 -d 3-medium
